begin;
select plan(18);
select has_table('public','salon_peche_rights','droits Pêche Salon créés');
select has_function('public','create_salon_peche_sale',array['text','integer','text','text','text','text','text','text','text','text','integer','date','text'],'RPC transactionnelle créée');
select has_function('public','admin_delete_salon_peche_item',array['uuid','uuid'],'suppression transactionnelle créée');
select col_is_pk('public','salon_peche_rights','id','clé primaire');
select col_is_unique('public','salon_peche_rights','sale_item_id','un droit par ligne');
select col_type_is('public','salon_peche_rights','valid_until','date','validité typée date');
select throws_ok($$select * from public.create_salon_peche_sale('inconnu',1,'A','B','1','', 'tpe','','',1,null,null)$$,'22023',null,'offre inconnue refusée');
select throws_ok($$select * from public.create_salon_peche_sale('peche_place_demi_journee',33000,'A','B','1','', 'tpe','','',1,null,null)$$,'22023',null,'place sans date refusée');
select lives_ok($$select * from public.create_salon_peche_sale('peche_privatisation_demi_journee',79000,'A','B','1','', 'tpe','','',4,null,null)$$,'privatisation différée autorisée');
select is((select montant_total from public.salon_sales order by created_at desc limit 1),79000,'privatisation demi-journée 79000');
select is((select valid_until from public.salon_sale_items order by created_at desc limit 1),date '2027-01-31','validité 2027-01-31');
select is((select nombre_personnes from public.salon_peche_rights order by created_at desc limit 1),4,'privatisation quatre personnes');
select lives_ok($$select * from public.create_salon_peche_sale('peche_2_plus_1_journee',80000,'C','D','2','', 'especes','','',3,null,null)$$,'2+1 différé autorisé');
select is((select montant_paye from public.salon_peche_rights where offer_code='peche_2_plus_1_journee' order by created_at desc limit 1),80000,'2+1 journée 80000 pour trois');
select is((select nombre_personnes from public.salon_peche_rights where offer_code='peche_2_plus_1_journee' order by created_at desc limit 1),3,'2+1 est une prestation pour trois');
select lives_ok(format($$select public.admin_delete_salon_peche_item(%L,%L)$$,(select sale_id from public.salon_sale_items where offer_code='peche_2_plus_1_journee' order by created_at desc limit 1),(select id from public.salon_sale_items where offer_code='peche_2_plus_1_journee' order by created_at desc limit 1)),'droit unused supprimable');
update public.salon_peche_rights set status='redeemed' where offer_code='peche_privatisation_demi_journee';
select throws_ok(format($$select public.admin_delete_salon_peche_item(%L,%L)$$,(select sale_id from public.salon_sale_items where offer_code='peche_privatisation_demi_journee' order by created_at desc limit 1),(select id from public.salon_sale_items where offer_code='peche_privatisation_demi_journee' order by created_at desc limit 1)),'P0001',null,'droit redeemed bloqué');
select is((select count(*)::integer from public.salon_peche_rights where status='redeemed'),1,'droit redeemed conservé');
select * from finish();
rollback;
