"use client";

import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { POINTURES_PALMES, TAILLES_COMBI } from "@/app/baleines/lib/rules";
import { getTahitiToday } from "@/lib/tahiti-date";

type Activity="baleines"|"peche"|"charter";
type Offer={activity:Activity;label:string;status:string;validUntil:string;total:number;paid:number;balance:number;participants:number;composition?:Record<string,number>;formula?:string;offerType?:string;reservedDate?:string|null;reservedEndDate?:string|null;reservedSlot?:string|null};
type Access={token:string;offer:Offer};
type Participant={prenom:string;nom:string;age:string;category:string;materielPerso:boolean;tailleCombinaison:string;pointurePalmes:string};
type Availability=Record<string,{used?:number;miseEau?:number;observateurs?:number;boatAvailable?:boolean}>;
const field="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white p-3 text-base";
const labels:Record<string,string>={baleines:"Baleines",peche:"Pêche",charter:"Charter",mise_eau:"Mise à l’eau",observateur:"Observateur",enfant_moins_12:"Enfant 5–11 ans",enfant_moins_5:"Enfant -5 ans"};
const money=(value:number)=>`${Number(value||0).toLocaleString("fr-FR")} F CFP`;
function previousDate(value:string){const date=new Date(`${value}T12:00:00Z`);date.setUTCDate(date.getUTCDate()-1);return date.toISOString().slice(0,10)}
function peopleFor(offer:Offer){const people:Participant[]=[];for(const [category,count] of Object.entries(offer.composition||{}))for(let index=0;index<Number(count);index++)people.push({prenom:"",nom:"",age:category==="enfant_moins_5"?"4":category==="enfant_moins_12"?"10":"",category,materielPerso:false,tailleCombinaison:"",pointurePalmes:""});return people}

export function ReprendreOffreClient(){
  const [reference,setReference]=useState(""),[contact,setContact]=useState(""),[offers,setOffers]=useState<Access[]>([]),[selected,setSelected]=useState<Access|null>(null);
  const [date,setDate]=useState(""),[slot,setSlot]=useState("morning"),[availability,setAvailability]=useState<Availability|null>(null),[charterAvailable,setCharterAvailable]=useState<boolean|null>(null);
  const [people,setPeople]=useState<Participant[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[confirmed,setConfirmed]=useState(false);
  const offer=selected?.offer; const expired=Boolean(offer&&offer.validUntil<getTahitiToday());
  const unavailable=useMemo(()=>{const pecheSlots=offer?.formula==="full_day"?["morning","afternoon"]:[slot];return !offer?false:offer.activity==="charter"?charterAvailable===false:offer.activity==="peche"?pecheSlots.some(value=>Boolean(availability?.[value]&&(!availability[value].boatAvailable||(offer.offerType==="privatisation"?Number(availability[value].used||0)>0:Number(availability[value].used||0)+offer.participants>4)))):Boolean(availability?.[slot]&&(!availability[slot].boatAvailable||Number(availability[slot].miseEau||0)+Number(offer.composition?.mise_eau||0)>6||Number(availability[slot].observateurs||0)+offer.participants-Number(offer.composition?.mise_eau||0)>2))},[availability,charterAvailable,offer,slot]);

  function choose(access:Access){setSelected(access);setDate("");setAvailability(null);setCharterAvailable(null);setConfirmed(false);setError("");setSlot(access.offer.activity==="baleines"?"07:00":"morning");setPeople(peopleFor(access.offer));}
  async function identify(event:FormEvent){event.preventDefault();setLoading(true);setError("");setOffers([]);setSelected(null);try{const response=await fetch("/api/salon/offers/identify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reference,contact})});const data=await response.json();if(!response.ok)throw new Error(data.error);setOffers(data.offers);if(data.offers.length===1)choose(data.offers[0]);}catch(cause){setError(cause instanceof Error?cause.message:"Offre introuvable ou informations incorrectes.")}finally{setLoading(false)}}
  async function chooseDate(value:string){setDate(value);setError("");setAvailability(null);setCharterAvailable(null);if(!value||!selected)return;try{const response=await fetch(`/api/salon/offers/availability?date=${encodeURIComponent(value)}`,{cache:"no-store",headers:{Authorization:`Bearer ${selected.token}`}});const data=await response.json();if(!response.ok)throw new Error(data.error);if(selected.offer.activity==="charter")setCharterAvailable(data.available);else setAvailability(data.availability);}catch(cause){setError(cause instanceof Error?cause.message:"Disponibilités indisponibles.")}}
  async function redeem(event:FormEvent){event.preventDefault();if(!selected)return;setLoading(true);setError("");try{const response=await fetch("/api/salon/offers/redeem",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${selected.token}`},body:JSON.stringify({date,slot,participants:selected.offer.activity==="baleines"?people:undefined})});const data=await response.json();if(!response.ok)throw new Error(data.error);setConfirmed(true);setSelected({...selected,offer:{...selected.offer,status:"redeemed",reservedDate:date,reservedSlot:selected.offer.activity==="charter"?null:slot}});}catch(cause){setError(cause instanceof Error?cause.message:"La réservation n’a pas pu être confirmée.")}finally{setLoading(false)}}
  const updatePerson=(index:number,change:Partial<Participant>)=>setPeople(current=>current.map((person,i)=>i===index?{...person,...change}:person));

  return <main className="min-h-screen bg-slate-100 px-4 py-8 text-slate-950"><div className="mx-auto max-w-3xl space-y-6">
    <header className="rounded-3xl bg-cyan-950 p-6 text-white shadow-xl md:p-9"><p className="font-black uppercase tracking-[.2em] text-cyan-200">Tahiti Trip Fishing</p><h1 className="mt-3 text-3xl font-black md:text-5xl">Réserver votre offre Salon</h1><p className="mt-4 max-w-2xl text-cyan-50">Vous avez acheté une prestation « Date à fixer » ? Retrouvez-la puis choisissez une disponibilité réelle.</p></header>
    {!selected&&<form onSubmit={identify} className="space-y-5 rounded-3xl bg-white p-5 shadow md:p-8"><h2 className="text-2xl font-black">1. Retrouver mon offre</h2><label className="block font-bold">Numéro de facture ou code offre<input required value={reference} onChange={event=>setReference(event.target.value)} autoComplete="off" className={field}/></label><label className="block font-bold">Téléphone ou e-mail utilisé lors de l’achat<input required value={contact} onChange={event=>setContact(event.target.value)} autoComplete="email" className={field}/></label><button disabled={loading} className="min-h-14 w-full rounded-xl bg-cyan-800 px-5 font-black text-white disabled:opacity-50">{loading?"VÉRIFICATION…":"RETROUVER MON OFFRE"}</button><p className="text-sm text-slate-600">Ces deux informations sont obligatoires. Elles ne créent pas de compte et l’accès temporaire expire automatiquement.</p></form>}
    {!selected&&offers.length>1&&<section className="space-y-3 rounded-3xl bg-white p-5 shadow"><h2 className="text-xl font-black">Choisissez votre offre</h2>{offers.map((access,index)=><button key={`${access.offer.activity}-${index}`} onClick={()=>choose(access)} className="min-h-14 w-full rounded-xl border p-4 text-left font-bold">{labels[access.offer.activity]} — {access.offer.label}</button>)}</section>}
    {offer&&<section className="space-y-5 rounded-3xl bg-white p-5 shadow md:p-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-black uppercase tracking-widest text-cyan-700">2. Mon offre</p><h2 className="mt-2 text-2xl font-black">{labels[offer.activity]} — {offer.label}</h2></div><button onClick={()=>{setSelected(null);setOffers([])}} className="rounded-lg border px-3 py-2 font-bold">Changer</button></div><dl className="grid gap-3 rounded-2xl bg-slate-50 p-4 sm:grid-cols-2"><div><dt>Participants</dt><dd className="font-black">{offer.participants}</dd></div><div><dt>Valable jusqu’au</dt><dd className="font-black">{new Date(`${offer.validUntil}T00:00:00Z`).toLocaleDateString("fr-FR",{timeZone:"UTC"})}</dd></div><div><dt>Total</dt><dd className="font-black">{money(offer.total)}</dd></div><div><dt>Déjà réglé</dt><dd className="font-black">{money(offer.paid)}</dd></div><div><dt>Solde restant</dt><dd className="font-black">{money(offer.balance)}</dd></div></dl>{offer.composition&&<p className="rounded-xl bg-cyan-50 p-4 font-bold">Composition : {Object.entries(offer.composition).filter(([,count])=>count>0).map(([key,count])=>`${count} ${labels[key]}`).join(" · ")}</p>}{offer.balance>0&&<p className="rounded-xl bg-amber-50 p-4 font-bold text-amber-900">{offer.activity==="charter"?"Solde à régler au plus tard la veille du départ.":"Solde à régler le jour de la prestation."}</p>}
      {(confirmed||offer.status==="redeemed")?<div className="rounded-2xl bg-emerald-100 p-5 text-emerald-900"><h3 className="text-xl font-black">Votre prestation est déjà réservée.</h3>{offer.reservedDate&&<p className="mt-2 font-bold">Date : {new Date(`${offer.reservedDate}T00:00:00Z`).toLocaleDateString("fr-FR",{timeZone:"UTC"})}{offer.reservedSlot?` · ${offer.reservedSlot}`:""}</p>}</div>:expired?<div className="rounded-2xl bg-red-100 p-5 font-black text-red-900">Cette offre est arrivée à expiration.</div>:<form onSubmit={redeem} className="space-y-5"><h3 className="text-xl font-black">3. Choisir une date</h3><label className="block font-bold">Date<input required type="date" min={getTahitiToday()} max={offer.activity==="charter"?previousDate(offer.validUntil):offer.validUntil} value={date} onChange={event=>void chooseDate(event.target.value)} className={field}/></label>{offer.activity!=="charter"&&<label className="block font-bold">Créneau<select value={slot} onChange={event=>setSlot(event.target.value)} className={field}>{offer.activity==="baleines"?<><option value="07:00">07:00</option><option value="13:15">13:15</option></>:offer.formula==="full_day"?<option value="morning">Journée complète</option>:<><option value="morning">Matin</option><option value="afternoon">Après-midi</option></>}</select></label>}{date&&<p className={`rounded-xl p-4 font-bold ${unavailable?"bg-red-100 text-red-900":"bg-emerald-100 text-emerald-900"}`}>{unavailable?"Cette date n’est pas disponible.":"Date disponible — une dernière vérification sera faite à la confirmation."}</p>}
      {offer.activity==="baleines"&&<section className="space-y-3"><h3 className="text-xl font-black">4. Informations participants</h3>{people.map((person,index)=><div key={`${person.category}-${index}`} className="grid gap-3 rounded-2xl border p-4 sm:grid-cols-2"><strong className="sm:col-span-2">{labels[person.category]}</strong><input required aria-label="Prénom" placeholder="Prénom" value={person.prenom} onChange={event=>updatePerson(index,{prenom:event.target.value})} className={field}/><input required aria-label="Nom" placeholder="Nom" value={person.nom} onChange={event=>updatePerson(index,{nom:event.target.value})} className={field}/><input required type="number" min="0" max="120" aria-label="Âge" placeholder="Âge" value={person.age} onChange={event=>updatePerson(index,{age:event.target.value})} className={field}/>{person.category==="mise_eau"&&<><label className="flex min-h-12 items-center font-bold"><input type="checkbox" checked={person.materielPerso} onChange={event=>updatePerson(index,{materielPerso:event.target.checked})} className="mr-3 size-5"/>J’ai mon matériel</label>{!person.materielPerso&&<><select required aria-label="Taille combinaison" value={person.tailleCombinaison} onChange={event=>updatePerson(index,{tailleCombinaison:event.target.value})} className={field}><option value="">Taille combinaison</option>{TAILLES_COMBI.map(value=><option key={value}>{value}</option>)}</select><select required aria-label="Pointure palmes" value={person.pointurePalmes} onChange={event=>updatePerson(index,{pointurePalmes:event.target.value})} className={field}><option value="">Pointure palmes</option>{POINTURES_PALMES.map(value=><option key={value}>{value}</option>)}</select></>}</>}</div>)}</section>}
      <button disabled={loading||!date||unavailable} className="min-h-14 w-full rounded-xl bg-cyan-800 px-5 font-black text-white disabled:opacity-50">{loading?"CONFIRMATION…":"CONFIRMER MA RÉSERVATION"}</button></form>}</section>}
    {error&&<p role="alert" className="rounded-2xl bg-red-100 p-4 font-bold text-red-900">{error}</p>}
    <aside className="rounded-3xl border border-cyan-200 bg-cyan-50 p-5"><h2 className="font-black">Vous avez un Carnet Baleines ?</h2><p className="mt-2 text-sm">Le carnet conserve son propre parcours et son système de crédits.</p><Link href="/baleines" className="mt-4 inline-flex min-h-12 items-center rounded-xl bg-white px-5 font-black text-cyan-900 shadow">UTILISER MON CARNET BALEINES</Link></aside>
    <Link href="/" className="inline-flex min-h-12 items-center font-bold text-cyan-900">← Retour à l’accueil</Link>
  </div></main>;
}
