"use client";
import { FormEvent, useMemo, useState } from "react";
import { formatSalonPrice } from "@/lib/salon-pricing";
import { SALON_PECHE_OFFERS, SALON_PECHE_VALID_UNTIL } from "@/lib/salonPeche";
import { SALON_PAYMENT_LABELS } from "@/lib/salonSales";
import { getTahitiToday } from "@/lib/tahiti-date";

type Props = { onRefresh: () => Promise<void>; openInvoice: (id: string) => Promise<void>; generateInvoice: (id: string) => Promise<string | null>; sendInvoice: (id: string) => Promise<boolean> };
const field = "mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white p-3";
export function SalonPecheForm({ onRefresh, openInvoice, generateInvoice, sendInvoice }: Props) {
  const [offerCode,setOfferCode]=useState<string>(SALON_PECHE_OFFERS[0].code); const offer=useMemo(()=>SALON_PECHE_OFFERS.find(o=>o.code===offerCode)!,[offerCode]);
  const [bookLater,setBookLater]=useState(true), [date,setDate]=useState(""), [departure,setDeparture]=useState("morning");
  const [people,setPeople]=useState(4);
  const [client,setClient]=useState({firstName:"",lastName:"",phone:"",email:"",paymentMethod:"tpe",paymentReference:"",comment:""});
  const [loading,setLoading]=useState(false),[error,setError]=useState(""),[created,setCreated]=useState<{saleId:string;label:string;total:number;invoiceNumber?:string|null}|null>(null);
  function choose(code:string){const next=SALON_PECHE_OFFERS.find(o=>o.code===code)!;setOfferCode(code);setPeople(next.people);if(!next.bookLater)setBookLater(false);if(next.formula==="full_day")setDeparture("morning");}
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");try{const response=await fetch("/api/admin/salon/peche",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({offerCode,bookLater,date,departure,people,...client})});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setCreated(payload);await onRefresh();}catch(c){setError(c instanceof Error?c.message:"Création impossible.");}finally{setLoading(false)}}
  if(created)return <section className="rounded-3xl bg-white p-6 shadow"><p className="font-black text-emerald-700">VENTE PÊCHE SALON ENREGISTRÉE</p><h2 className="mt-3 text-2xl font-black">{created.label}</h2><p className="text-xl font-black">{formatSalonPrice(created.total)}</p><div className="mt-5 flex flex-wrap gap-3">{created.invoiceNumber?<button className="rounded-xl bg-cyan-800 px-5 py-3 font-bold text-white" onClick={()=>void openInvoice(created.saleId)}>Voir la facture</button>:<button className="rounded-xl bg-amber-600 px-5 py-3 font-bold text-white" onClick={async()=>{const n=await generateInvoice(created.saleId);if(n)setCreated({...created,invoiceNumber:n})}}>Générer la facture</button>}{created.invoiceNumber&&client.email&&<button className="rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white" onClick={()=>void sendInvoice(created.saleId)}>Envoyer par e-mail</button>}<button className="rounded-xl border px-5 py-3 font-bold" onClick={()=>setCreated(null)}>Nouvelle vente</button></div></section>;
  const groups=[{kind:"privatisation",title:"1. Privatisation — offre principale"},{kind:"place",title:"2. Une place"},{kind:"two_plus_one",title:"3. Offre 2+1"}] as const;
  return <form onSubmit={submit} className="space-y-6 rounded-3xl bg-white p-5 shadow md:p-8"><div><h2 className="text-3xl font-black">Vente Pêche Salon</h2><p className="font-bold text-amber-800">Valable jusqu’au 31 janvier 2027</p></div>{groups.map((g,i)=><section key={g.kind} className={i===0?"rounded-3xl border-4 border-cyan-700 bg-cyan-50 p-5":"rounded-2xl border p-5"}><h3 className="text-xl font-black">{g.title}</h3>{g.kind==="place"&&<p className="mt-2 rounded-lg bg-amber-100 p-3 font-black text-amber-900">Date de sortie obligatoire le jour de l&apos;achat.</p>}<div className="mt-3 grid gap-3 md:grid-cols-2">{SALON_PECHE_OFFERS.filter(o=>o.kind===g.kind).map(o=><label key={o.code} className={`rounded-xl border-2 p-4 ${offerCode===o.code?"border-cyan-700 bg-white":"border-slate-200"}`}><input type="radio" checked={offerCode===o.code} onChange={()=>choose(o.code)} className="mr-2"/><strong>{o.formula==="half_day"?"Demi-journée":"Journée"}</strong><span className="block text-2xl font-black">{formatSalonPrice(o.price)}</span><span className="text-sm">{o.kind==="privatisation"?"Bateau privatisé, jusqu’à 4 pêcheurs":`${o.people} personne${o.people>1?"s":""} sur la même sortie`}</span></label>)}</div></section>)}
  {offer.bookLater&&<section><h3 className="font-black">Planification</h3><div className="mt-2 flex gap-4"><label><input type="radio" checked={!bookLater} onChange={()=>setBookLater(false)}/> Réserver maintenant</label><label><input type="radio" checked={bookLater} onChange={()=>setBookLater(true)}/> Date à fixer plus tard</label></div></section>}
  {offer.kind==="privatisation"&&<label className="block font-bold">Nombre de pêcheurs (1 à 4)<select className={field} value={people} onChange={e=>setPeople(Number(e.target.value))}>{[1,2,3,4].map(value=><option key={value}>{value}</option>)}</select></label>}
  {!bookLater&&<div className="grid gap-4 md:grid-cols-2"><label className="font-bold">Date *<input required type="date" min={getTahitiToday()} max={SALON_PECHE_VALID_UNTIL} className={field} value={date} onChange={e=>setDate(e.target.value)}/></label>{offer.formula==="half_day"&&<label className="font-bold">Départ *<select className={field} value={departure} onChange={e=>setDeparture(e.target.value)}><option value="morning">Matin</option><option value="afternoon">Après-midi</option></select></label>}</div>}
  <div className="grid gap-4 md:grid-cols-2">{(["firstName","lastName","phone","email"] as const).map((key)=><label key={key} className="font-bold">{{firstName:"Prénom *",lastName:"Nom *",phone:"Téléphone *",email:"E-mail (facultatif)"}[key]}<input required={key!=="email"} type={key==="email"?"email":"text"} className={field} value={client[key]} onChange={e=>setClient({...client,[key]:e.target.value})}/></label>)}</div>
  <section><h3 className="font-black">Paiement</h3><div className="mt-2 grid gap-2 sm:grid-cols-4">{Object.entries(SALON_PAYMENT_LABELS).map(([value,label])=><label key={value} className="rounded-xl border p-3 font-bold"><input type="radio" checked={client.paymentMethod===value} onChange={()=>setClient({...client,paymentMethod:value})}/> {label}</label>)}</div>{(client.paymentMethod==="cheque"||client.paymentMethod==="virement")&&<label className="font-bold">Référence<input className={field} value={client.paymentReference} onChange={e=>setClient({...client,paymentReference:e.target.value})}/></label>}</section>
  <label className="block font-bold">Commentaire interne<textarea className={field} value={client.comment} onChange={e=>setClient({...client,comment:e.target.value})}/></label>{error&&<p className="rounded-xl bg-red-100 p-4 font-bold text-red-800">{error}</p>}<button disabled={loading} className="min-h-14 w-full rounded-2xl bg-cyan-800 px-5 font-black text-white">{loading?"Enregistrement…":`Enregistrer · ${formatSalonPrice(offer.price)}`}</button></form>;
}
