"use client";

import { FormEvent, useState } from "react";
import { SALON_PRICING, formatSalonPrice } from "@/lib/salon-pricing";
import { SALON_PAYMENT_LABELS, getSalonCarnetOffer, getSalonCarnetValidityLabel } from "@/lib/salonSales";

type Created = { saleId: string; carnetId: string; carnetCode: string; invoiceNumber: string | null; emailAvailable: boolean; warning?: string };
type Props = { onRefresh: () => Promise<void>; openInvoice: (id: string) => Promise<void>; generateInvoice: (id: string) => Promise<string | null>; sendInvoice: (id: string) => Promise<boolean> };

export function SalonCarnetForm({ onRefresh, openInvoice, generateInvoice, sendInvoice }: Props) {
  const [form, setForm] = useState({ offerCode: SALON_PRICING.baleines.carnets[0].offerCode, firstName: "", lastName: "", phone: "", email: "", paymentMethod: "tpe", paymentReference: "", comment: "" });
  const [created, setCreated] = useState<Created | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const selected = getSalonCarnetOffer(form.offerCode)!;
  function update(name: string, value: string) { setForm((current) => ({ ...current, [name]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/admin/salon/carnets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setCreated(payload); await onRefresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Création impossible."); } finally { setLoading(false); } }
  const field = "mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white p-3";

  if (created) return <section className="rounded-3xl bg-white p-6 shadow md:p-8"><p className="font-black uppercase tracking-widest text-emerald-700">VENTE CARNET BALEINES ENREGISTRÉE</p><h2 className="mt-3 text-3xl font-black">{form.firstName} {form.lastName}</h2>{created.warning && <p className="mt-4 rounded-xl bg-amber-100 p-4 font-bold text-amber-900">{created.warning}</p>}<dl className="mt-6 grid gap-4 sm:grid-cols-2"><Data label="Offre" value={selected.label}/><Data label="Code carnet" value={created.carnetCode}/><Data label="Crédits" value={String(selected.credits)}/><Data label="Tarif" value={formatSalonPrice(selected.price)}/><Data label="Paiement" value={SALON_PAYMENT_LABELS[form.paymentMethod as keyof typeof SALON_PAYMENT_LABELS]}/><Data label="Validité" value={getSalonCarnetValidityLabel()}/></dl>{message && <p className="mt-4 rounded-xl bg-emerald-100 p-4 font-bold text-emerald-800">{message}</p>}<div className="mt-7 flex flex-wrap gap-3">{created.invoiceNumber ? <button onClick={() => void openInvoice(created.saleId)} className="rounded-xl bg-cyan-800 px-5 py-3 font-bold text-white">Voir / télécharger la facture</button> : <button disabled={loading} onClick={async () => { setLoading(true); const number = await generateInvoice(created.saleId); setLoading(false); if (number) setCreated({ ...created, invoiceNumber: number, warning: undefined }); }} className="rounded-xl bg-amber-600 px-5 py-3 font-bold text-white">Générer la facture</button>}{created.emailAvailable && created.invoiceNumber && <button disabled={loading} onClick={async () => { setLoading(true); if (await sendInvoice(created.saleId)) setMessage("Facture envoyée par e-mail."); setLoading(false); }} className="rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white">Envoyer la facture par e-mail</button>}<button onClick={() => { setCreated(null); setForm((current) => ({ ...current, firstName: "", lastName: "", phone: "", email: "", paymentReference: "", comment: "" })); }} className="rounded-xl border px-5 py-3 font-bold">Nouvelle vente Salon</button></div></section>;

  return <form onSubmit={submit} className="space-y-5 rounded-3xl bg-white p-5 shadow md:p-8"><div><p className="font-black uppercase tracking-widest text-cyan-700">Baleines · Carnets</p><h2 className="mt-2 text-2xl font-black">Nouveau carnet Baleines Salon</h2></div><div className="grid gap-4 sm:grid-cols-2">{SALON_PRICING.baleines.carnets.map((offer) => <label key={offer.offerCode} className={`rounded-2xl border-2 p-5 ${form.offerCode === offer.offerCode ? "border-cyan-700 bg-cyan-50" : "border-slate-200"}`}><input type="radio" className="mr-2" checked={form.offerCode === offer.offerCode} onChange={() => update("offerCode", offer.offerCode)}/><strong>CARNET {offer.sorties} SORTIES</strong><span className="mt-2 block text-2xl font-black">{formatSalonPrice(offer.total)}</span><span className="text-sm text-slate-500">Tarif normal : {formatSalonPrice(offer.normal)}</span></label>)}</div><p className="font-bold text-amber-800">Valable jusqu’au {getSalonCarnetValidityLabel()}</p><div className="grid gap-4 md:grid-cols-2"><Field label="Prénom *"><input required className={field} value={form.firstName} onChange={(e) => update("firstName", e.target.value)}/></Field><Field label="Nom *"><input required className={field} value={form.lastName} onChange={(e) => update("lastName", e.target.value)}/></Field><Field label="Téléphone *"><input required className={field} value={form.phone} onChange={(e) => update("phone", e.target.value)}/></Field><Field label="E-mail (facultatif)"><input type="email" className={field} value={form.email} onChange={(e) => update("email", e.target.value)}/></Field></div><section><h3 className="text-lg font-black">Paiement</h3><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(SALON_PAYMENT_LABELS).map(([value, label]) => <label key={value} className="rounded-xl border p-4 font-bold"><input type="radio" className="mr-2" checked={form.paymentMethod === value} onChange={() => update("paymentMethod", value)}/>{label}</label>)}</div>{(form.paymentMethod === "cheque" || form.paymentMethod === "virement") && <Field label="Référence (facultative)"><input className={field} value={form.paymentReference} onChange={(e) => update("paymentReference", e.target.value)}/></Field>}</section><Field label="Commentaire interne"><textarea className={field} rows={3} value={form.comment} onChange={(e) => update("comment", e.target.value)}/></Field>{error && <p className="rounded-xl bg-red-100 p-4 font-bold text-red-800">{error}</p>}<button disabled={loading} className="min-h-14 w-full rounded-2xl bg-emerald-700 px-5 text-lg font-black text-white disabled:bg-slate-400">{loading ? "Enregistrement…" : `Créer le carnet · ${formatSalonPrice(selected.price)}`}</button></form>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block font-bold">{label}{children}</label>; }
function Data({ label, value }: { label: string; value: string }) { return <div><dt className="text-sm text-slate-500">{label}</dt><dd className="font-black">{value}</dd></div>; }
