import { NextResponse } from "next/server";
import { verifyAdminSession } from "@/lib/adminSession";
import { getSalonAdminClient } from "@/lib/salonAdmin";
import { getCharterSlotRequirements, isValidIsoDate } from "@/lib/charter-availability";
import { isSalonPaymentMethod } from "@/lib/salonSales";
import { SALON_CHARTER_VALID_UNTIL, validateSalonCharterPurchase } from "@/lib/salonCharter";
import { getTahitiToday } from "@/lib/tahiti-date";
const EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/; const text=(v:unknown)=>typeof v==="string"?v.trim():"";
export async function GET(request:Request){if(!verifyAdminSession(request))return NextResponse.json({error:"Accès admin refusé."},{status:401});const date=new URL(request.url).searchParams.get("date")||"";if(!isValidIsoDate(date))return NextResponse.json({error:"Date invalide."},{status:400});const {requiredSlots,endDate}=getCharterSlotRequirements("tetiaroa_2j_1n",date);const result=await getSalonAdminClient().from("boat_calendar_slots").select("date,slot,status,activity,expires_at").in("date",[date,endDate]);if(result.error)return NextResponse.json({error:"Disponibilités indisponibles."},{status:500});const now=Date.now();const conflicts=(result.data||[]).filter(row=>requiredSlots.some(slot=>slot.date===row.date&&slot.slot===row.slot)&&row.status!=="available"&&!(row.status==="hold"&&row.expires_at&&new Date(row.expires_at).getTime()<=now));return NextResponse.json({available:conflicts.length===0,endDate,conflicts});}
export async function POST(request:Request){if(!verifyAdminSession(request))return NextResponse.json({error:"Accès admin refusé."},{status:401});try{const body=await request.json() as Record<string,unknown>;if(["price","total","unit_price","total_price","montant_total"].some(k=>k in body))return NextResponse.json({error:"Le prix est déterminé exclusivement par le serveur."},{status:400});const validation=validateSalonCharterPurchase({offerCode:body.offerCode,participants:body.participants,sleepingAccepted:body.sleepingAccepted});if("error" in validation)return NextResponse.json({error:validation.error},{status:400});const firstName=text(body.firstName),lastName=text(body.lastName),phone=text(body.phone),email=text(body.email).toLowerCase();if(!firstName||!lastName||!phone||(email&&!EMAIL.test(email)))return NextResponse.json({error:"Coordonnées client invalides."},{status:400});if(!isSalonPaymentMethod(body.paymentMethod))return NextResponse.json({error:"Moyen de paiement invalide."},{status:400});const bookLater=body.bookLater===true,date=bookLater?"":text(body.date);if(!bookLater&&(!isValidIsoDate(date)||date<getTahitiToday()||date>SALON_CHARTER_VALID_UNTIL))return NextResponse.json({error:"Date Charter invalide."},{status:400});const slots=bookLater?[]:getCharterSlotRequirements("tetiaroa_2j_1n",date).requiredSlots;const rpc=await getSalonAdminClient().rpc("create_salon_charter_sale",{p_offer_code:validation.offer.code,p_price:validation.offer.price,p_prenom:firstName,p_nom:lastName,p_telephone:phone,p_email:email,p_nombre_personnes:validation.participants,p_sleeping_accepted:body.sleepingAccepted===true,p_payment_method:body.paymentMethod,p_payment_reference:text(body.paymentReference),p_commentaire:text(body.comment),p_date_debut:date||null,p_requested_slots:slots});if(rpc.error){const conflict=/conflit|indisponible/i.test(rpc.error.message);return NextResponse.json({error:conflict?"Les dates Charter ne sont plus disponibles.":rpc.error.message},{status:conflict?409:400})}const result=Array.isArray(rpc.data)?rpc.data[0]:rpc.data;return NextResponse.json({saleId:result.sale_id,reservationId:result.reservation_id,rightId:result.right_id,label:validation.offer.label,total:validation.offer.price},{status:201})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Création Charter Salon impossible."},{status:400})}}
